development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

## MySQL
production:
  database: tillsammans
  adapter: mysql
  hostname: localhost
  username: tillsammans
#  password: ...

## Sqlite3
#production:
#  adapter: sqlite3
#  database: db/production.sqlite3
#  timeout: 5000
